name: GitHub Pages Build

on:
  [push, pull_request]

defaults:
  run:
    shell: bash -l {0}

jobs:
  build_qutip_jupyterlite:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Mambaforge
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-variant: Mambaforge
        miniforge-version: latest
        use-mamba: true

    - name: Install jupyterlite and requirements
      run: |
        pip install virtualenv
        virtualenv --python python3.10 venv
        source venv/bin/activate
        pip install -r requirements.txt
        mamba install empack==0.8.2

    - name: Environment information
      run: |
        source venv/bin/activate
        pip freeze
        mamba list

    - name: Download qutip-tutorials
      run: |
        source venv/bin/activate
        wget -O qutip-tutorials-main.zip https://github.com/qutip/qutip-tutorials/archive/main.zip
        mkdir lite/files/tutorials
        TUTDIR=$(pwd)/lite/files/tutorials
        unzip qutip-tutorials-main.zip
        cd qutip-tutorials-main/tutorials-v4
        find . -name '*.md' -exec jupytext --to notebook {} +
        find . -name '*.ipynb' -exec cp -t ${TUTDIR} --parents {} +
        cd -
        rm ${TUTDIR}/template.ipynb
        rm -rf qutip-tutorials-main.zip qutip-tutorials-main

    - name: Build QuTiP jupyterlite
      run: |
        source venv/bin/activate
        ./scripts/jl-build-qutip
        touch _output/.nojekyll

    - name: Store QuTiP jupyterlite artifact
      uses: actions/upload-artifact@v3
      with:
        name: qutip-jupyterlite
        path: |
          _output

  publish_to_ghpages:
    needs: build_qutip_jupyterlite
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'hodgestar/try-qutip' && github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@master
        with:
          name: qutip-jupyterlite
          path: publish/

      - name: Publish to GitHub Pages
        run: |
          python -m pip install ghp-import
          ghp-import -m "Automatic push by ghp-import" -f -n -p -o -r origin -b gh-pages publish
